// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package database

import (
	"context"
	"database/sql"
)

const deleteMessage = `-- name: DeleteMessage :exec
;


DELETE from  Messages where chat_id = ? and id = ?
`

type DeleteMessageParams struct {
	ChatID sql.NullInt64
	ID     int64
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.ExecContext(ctx, deleteMessage, arg.ChatID, arg.ID)
	return err
}

const getMessageId = `-- name: GetMessageId :one
select id, sender_id, chat_id, content, sent_at from Messages where id = ? order by sent_at desc
`

func (q *Queries) GetMessageId(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessageId, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ChatID,
		&i.Content,
		&i.SentAt,
	)
	return i, err
}

const getMessagesByChatId = `-- name: GetMessagesByChatId :many
;

select id, sender_id, chat_id, content, sent_at from Messages where sender_id= ? order by sent_at desc
`

func (q *Queries) GetMessagesByChatId(ctx context.Context, senderID interface{}) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByChatId, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.ChatID,
			&i.Content,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const newMessage = `-- name: NewMessage :one
INSERT INTO Messages(sender_id,chat_id , content, sent_at)

VALUES (
    ?,
    ?,
    ?,
    NOW()

)
RETURNING id, sender_id, chat_id, content, sent_at
`

type NewMessageParams struct {
	SenderID interface{}
	ChatID   sql.NullInt64
	Content  string
}

func (q *Queries) NewMessage(ctx context.Context, arg NewMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, newMessage, arg.SenderID, arg.ChatID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ChatID,
		&i.Content,
		&i.SentAt,
	)
	return i, err
}
