// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Chat struct {
	ID           uuid.UUID
	CreationDate time.Time
}

type ChatMember struct {
	ChatID   interface{}
	UserID   interface{}
	JoinDate time.Time
}

type Message struct {
	ID       uuid.UUID
	SenderID interface{}
	ChatID   interface{}
	Content  string
	SentAt   time.Time
}

type User struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Email     string
	Password  string
	Username  string
}
